# Add an empty line between prompts
add_newline = false

# The left prompt
format = """
$directory \
"""

# The right prompt
right_format="""
$git_branch\
$git_status\
$python\
$lua\
$nodejs
"""

# Use a one line prompt instead of the default two line
[line_break]
disabled = true

# Shows failure character if last command failed. Success otherwise
[character]
success_symbol = "[♥](fg:#06969A bg:#1C658C)"
error_symbol = "[♥](green bg:#1C658C) "

[directory]
read_only = " "
format = "[](fg:#1C658C)[$read_only $path ]($style)[](fg:#1C658C)"
style = "bg:#1C658C fg:#D8DDE3"

[git_branch]
symbol = ""
format = "[](fg:#E76062)[ $symbol $branch ]($style)[](fg:#E76062)"
style = "bg:#e76062 fg:#D8DDE3"

# show number of changed files and such stuff
[git_status]
untracked = " $count "
modified = " $count "
stashed = " $count "
staged = " $count "
renamed = "凜$count "
deleted = "﫧$count "
up_to_date = ""
ahead = "祝$count"
behind = " $count"
format = "[](fg:#A24850)[ $all_status$ahead_behind ]($style)[](fg:#A24850)"
style = "fg:#D8DDE3 bg:#A24850"

[python]
symbol = ""
# using python brand colors
format = "[](fg:#306998)[$symbol $version (\\($virtualenv\\))]($style)[](fg:#306998)"
style = "fg:#FFD43B bg:#306998"

[lua]
symbol = ""
format = "[](fg:#00007C)[$symbol $version]($style)[](fg:#00007C)"
# using lua brand colors
style = "fg:#D8DDE3 bg:#00007C"
lua_binary = "luajit"

[nodejs]
symbol = ""
# using nodejs brand colors
format = "[](fg:#68A063)[$symbol $version]($style)[](fg:#68A063)"
style = "fg:#303030 bg:#68A063"
